#!/bin/bash
# =============================================================================
# Sample- and variant-level quality control
#
# Study : Shared genetic architecture of metabolic syndrome and prediction of
#         coexisting metabolic syndrome and type 2 diabetes (Taiwan Biobank)
#
# Input : Taiwan Biobank v2.0 genotype data (PLINK binary format)
#           - ${GENO_IMPUTED} : imputed genotypes, GRCh38
#           - ${GENO_ARRAY}   : directly genotyped array data, GRCh38
#           - SAMPLE6.tab / SAMPLE4.tab : participant IDs for the training (60%)
#                                         and testing (40%) sets
#
# Output: qc6-final.{bed,bim,fam} : post-QC training set
#         qc4-final.{bed,bim,fam} : post-QC testing set
#         pca6.eigenvec / pca4.eigenvec : genetic principal components
#
# Software: PLINK v1.90b6.x, PLINK v2.00a3.x   <-- TODO: insert exact versions
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# 0. Configuration -- edit these paths only
# ---------------------------------------------------------------------------
WORKDIR="./data"                       # working directory
GENO_IMPUTED="TWB2.hg38.impu.v4"       # imputed genotype dataset
GENO_ARRAY="TWB2.hg38.v4"              # array (non-imputed) dataset
THREADS=48

PLINK1="plink"                         # PLINK 1.9 executable
PLINK2="plink2"                        # PLINK 2.0 executable

cd "${WORKDIR}"

# Individual-level Taiwan Biobank data are not redistributable; the input files
# above must be obtained directly from the Taiwan Biobank
# (https://www.twbiobank.org.tw/) under an approved data access application.

# ---------------------------------------------------------------------------
# 1. Randomly partition the cohort 6:4 into training and testing sets
#    (SAMPLE6.tab / SAMPLE4.tab are generated beforehand by simple random
#     sampling without replacement; see 01_qc/make_split.R)
# ---------------------------------------------------------------------------
for SET in 6 4; do
  ${PLINK2} \
    --bfile "${GENO_IMPUTED}" \
    --threads ${THREADS} \
    --keep "SAMPLE${SET}.tab" \
    --make-bed \
    --out "sample${SET}"
done

# ---------------------------------------------------------------------------
# 2. Sample QC step 1 -- genotyping call rate
#    Exclude individuals with a call rate below 95% (--mind 0.05)
# ---------------------------------------------------------------------------
for SET in 6 4; do
  ${PLINK1} \
    --bfile "sample${SET}" \
    --threads ${THREADS} \
    --mind 0.05 \
    --make-bed \
    --out "qc${SET}_1"
done

# ---------------------------------------------------------------------------
# 3. Sample QC step 2 -- heterozygosity
#    Compute observed heterozygosity, then exclude individuals whose rate
#    deviates by more than 3 SD from the sample mean.
#    The exclusion list is generated by 01_qc/het_outliers.R
# ---------------------------------------------------------------------------
for SET in 6 4; do
  ${PLINK1} \
    --bfile "qc${SET}_1" \
    --threads ${THREADS} \
    --het \
    --out "het${SET}"
done

Rscript ../01_qc/het_outliers.R het6.het fail-het-qc6.txt
Rscript ../01_qc/het_outliers.R het4.het fail-het-qc4.txt

for SET in 6 4; do
  ${PLINK1} \
    --bfile "qc${SET}_1" \
    --remove "fail-het-qc${SET}.txt" \
    --make-bed \
    --out "qc${SET}_2"
done

# ---------------------------------------------------------------------------
# 4. Sample QC step 3 -- cryptic relatedness
#    LD-prune, then estimate identity-by-descent. Pairs with PI_HAT >= 0.1875
#    (third-degree or closer) are identified and one member of each pair is
#    excluded.
#
#    NOTE: 01_qc/related_exclusion.R selects the member of each pair with the
#    higher genotype missingness rate, which requires the --missing output
#    produced below. If you instead excluded the first listed individual of
#    each pair, use the commented-out PLINK line and amend the manuscript
#    Methods accordingly.
# ---------------------------------------------------------------------------
for SET in 6 4; do
  ${PLINK1} \
    --bfile "qc${SET}_2" \
    --threads ${THREADS} \
    --indep-pairwise 200 5 0.2 \
    --out "indep${SET}"

  ${PLINK1} \
    --bfile "qc${SET}_2" \
    --extract "indep${SET}.prune.in" \
    --genome --min 0.1875 \
    --out "related${SET}"

  ${PLINK1} \
    --bfile "qc${SET}_2" \
    --missing \
    --out "miss${SET}"

  Rscript ../01_qc/related_exclusion.R \
    "related${SET}.genome" "miss${SET}.imiss" "fail-related-qc${SET}.txt"

  ${PLINK1} \
    --bfile "qc${SET}_2" \
    --remove "fail-related-qc${SET}.txt" \
    --make-bed \
    --out "qc${SET}_3"

  # Alternative used in the original analysis (removes FID1/IID1 of each pair):
  # ${PLINK1} --bfile "qc${SET}_2" --remove "related${SET}.genome" \
  #           --make-bed --out "qc${SET}_3"
done

# ---------------------------------------------------------------------------
# 5. Sample QC step 4 -- sex concordance
#    Genetically inferred sex from X-chromosome genotypes is compared with
#    self-reported sex. Performed on array (non-imputed) data, since imputed
#    X-chromosome dosages are not suitable for --check-sex.
#    Discordant individuals are listed in fail-sex-qc{6,4}.txt and removed.
# ---------------------------------------------------------------------------
for SET in 6 4; do
  ${PLINK2} \
    --bfile "${GENO_ARRAY}" \
    --threads ${THREADS} \
    --keep "qc${SET}_3.fam" \
    --make-bed \
    --out "qc${SET}_4"

  ${PLINK2} \
    --bfile "qc${SET}_4" \
    --threads ${THREADS} \
    --split-par b38 \
    --make-bed \
    --out "qc${SET}_5"

  ${PLINK2} \
    --bfile "qc${SET}_5" \
    --threads ${THREADS} \
    --indep-pairwise 200 5 0.2 \
    --out "indep${SET}2"

  ${PLINK2} \
    --bfile "qc${SET}_5" \
    --threads ${THREADS} \
    --extract "indep${SET}2.prune.in" \
    --check-sex \
    --out "checksex${SET}"

  # TODO: confirm how the PROBLEM rows in checksex{6,4}.sexcheck were converted
  #       into fail-sex-qc{6,4}.txt, then uncomment the removal step below.
  # ${PLINK1} --bfile "qc${SET}_3" --remove "fail-sex-qc${SET}.txt" \
  #           --make-bed --out "qc${SET}_6"
done

# ---------------------------------------------------------------------------
# 6. Variant QC
#    Call rate >= 95% (--geno 0.05), MAF >= 1% (--maf 0.01) and
#    Hardy-Weinberg equilibrium p >= 1e-6 (--hwe 0.000001).
#
#    Imputation quality: variants with an INFO score < 0.8 were excluded.
#    TODO: insert the command or filtering step used for the INFO threshold
#          (e.g. --extract of a pre-filtered variant list, or the qctool/bgenix
#          step applied to the imputed data before conversion to PLINK format).
# ---------------------------------------------------------------------------
for SET in 6 4; do
  ${PLINK1} \
    --bfile "qc${SET}_3" \
    --threads ${THREADS} \
    --geno 0.05 \
    --maf 0.01 \
    --hwe 0.000001 \
    --make-bed \
    --out "qc${SET}-final"
done

# ---------------------------------------------------------------------------
# 7. Principal component analysis on the post-QC data
#    LD-pruned variants are used to compute genetic principal components,
#    which are supplied as covariates in the association analyses.
# ---------------------------------------------------------------------------
for SET in 6 4; do
  ${PLINK1} \
    --bfile "qc${SET}-final" \
    --threads ${THREADS} \
    --indep-pairwise 200 5 0.2 \
    --out "indep${SET}3"

  ${PLINK1} \
    --bfile "qc${SET}-final" \
    --extract "indep${SET}3.prune.in" \
    --pca header \
    --out "pca${SET}"
done

# The eigenvalues in pca{6,4}.eigenval were inspected on a scree plot to decide
# how many components to retain as covariates (see manuscript ESM Methods).

echo "QC complete."
echo "Training set : qc6-final  |  Testing set : qc4-final"
